PREP(currentSlot);
PREP(onRightPanelFilled);
PREP(collapsePanel);
PREP(onSelChangedRight);
PREP(refreshOptions);
PREP(generateOptionsUI);
PREP(refreshCheckboxes);
PREP(changeCurrentConfig);
PREP(onValueButton);
