"""Generate the ACEAX XtdGearModels / XtdGearInfos trees for the mod in tools/mod.yml.

Reads the derapified configs in _dump/ (see dump_configs.py) plus the hand-written
judgement calls in tools/overrides.yml, and writes addons/main/. Idempotent: running
it twice produces no diff.

Usage:
    python tools/gen_aceax.py            # write the config
    python tools/gen_aceax.py --check    # report only, write nothing
"""

from __future__ import annotations

import argparse
import collections
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent))

# These scripts print mod-authored display names, and Windows consoles default to
# a legacy codepage that cannot encode them -- RHS writes some Soviet loads in
# Cyrillic ("7Т3М"), which crashed `report.py --coverage` outright. Reconfigure
# stdout rather than stripping the names: the point of the report is to show what
# the mod actually calls things.
sys.stdout.reconfigure(encoding="utf-8", errors="replace")

import modinfo  # noqa: E402
from modconfig import Config, Item, decompose_display_name, unproven_variants  # noqa: E402

REPO = modinfo.REPO
ADDON = modinfo.ADDON
OVERRIDES = modinfo.OVERRIDES

BANNER = "// Generated by tools/gen_aceax.py -- do not edit by hand.\n"


@dataclass
class Member:
    item: Item
    values: dict[str, str]


@dataclass
class Model:
    pack: str
    config_root: str
    label: str
    name: str
    author: str
    axes: list[str] = field(default_factory=list)
    axis_values: dict[str, list[str]] = field(default_factory=dict)
    members: list[Member] = field(default_factory=list)
    sparse: bool = False
    member_packs: tuple[str, ...] = ()  # >1 means the entry spans sources


# ---------------------------------------------------------------------------
# grouping
# ---------------------------------------------------------------------------


def slug(text: str) -> str:
    out = re.sub(r"[^a-z0-9]+", "_", text.lower()).strip("_")
    return re.sub(r"_+", "_", out)


def collect(config: Config, ov: dict) -> tuple[list[Model], list[str], set[str]]:
    splitters: dict[str, str] = ov["splitters"]
    # Token matching is case-SENSITIVE, and deliberately so: NIArms distinguishes
    # "TAC" (a rail kit) from "Tac" (a receiver configuration) by capitalisation
    # alone. A mod that is merely inconsistent with itself -- MilGP writes both
    # "MC ARID" and "MC Arid" -- lists both spellings instead.
    #
    # str() guards against YAML 1.1 turning a bare YES/NO/ON/OFF value into a bool
    tokens = {k: (a, str(v)) for k, (a, v) in ov["tokens"].items()}
    suffixes = {k: (a, str(v)) for k, (a, v) in ov["class_suffixes"].items()}
    # Mirror of class_suffixes for mods that put the discriminator at the front.
    # Tier One ships every accessory once per weapon platform -- 23 classes all
    # called "LA-5B" -- and only the class name says which is which:
    #   Tier1_10_LA5_Side, Tier1_416_LA5_Side, Tier1_MCX_LA5_Side, ...
    prefixes = {k: (a, str(v)) for k, (a, v) in (ov.get("class_prefixes") or {}).items()}
    per_item: dict[str, dict] = {k.lower(): v for k, v in (ov.get("weapons") or {}).items()}
    opts: dict[str, dict] = ov["options"]

    # When a marker holds several values they may describe different PARTS of one
    # item rather than alternatives -- a uniform's top and its trousers. Where that
    # is so, the Nth mapped token is moved onto the Nth axis listed here, whatever
    # axis the token table gave it. Splitter tokens are not counted.
    positional = [str(a) for a in (ov.get("positional_axes") or [])]

    unknown: set[str] = set()
    grouped: dict[tuple[str, str], list[Member]] = collections.defaultdict(list)
    forced_pack: dict[tuple[str, str], str] = {}

    bases: dict[str, dict] = ov.get("bases") or {}

    # Names built by composition -- "Micro T-2/Leap/G33/LT 5/8". Absent for most
    # mods, in which case decompose_display_name is exactly parse_display_name.
    # Note the `bases:` lookup below is keyed on the DECOMPOSED base, so a rule
    # there matches the stem rather than every composition of it.
    compose: dict = ov.get("compose") or {}

    # Display-name mirror of class_prefixes, for mods that write the discriminator
    # on the FRONT of the name rather than in a "(...)" marker. VSM names every
    # vest "[VSM] <camo> <model> (<role>)", so one vest arrives under fifteen base
    # names. Longest first: "Multicam Arid" has to beat "Multicam".
    #
    # `keep` is the constant tag that survives at the front of the base -- VSM
    # prefixes everything with "[VSM] " and that is worth keeping in the arsenal,
    # so the match is made after it and it is put back.
    name_prefixes = sorted(
        ((str(k), (str(a), str(v))) for k, (a, v) in (ov.get("name_prefixes") or {}).items()),
        key=lambda kv: -len(kv[0]),
    )
    name_prefix_keep = str(ov.get("name_prefix_keep") or "")

    for item in config.arsenal_items():
        base, toks, parts = decompose_display_name(item.display_name, compose)
        values: dict[str, str] = {}
        extra: list[str] = []
        pack_override: str | None = None

        # Cut a leading discriminator out of the base name. Runs BEFORE the `bases:`
        # lookup so a rule there is written against the stem, not against every
        # prefixed spelling of it.
        if name_prefixes and base.startswith(name_prefix_keep):
            rest = base[len(name_prefix_keep):]
            for prefix, (axis, value) in name_prefixes:
                if rest.startswith(prefix):
                    values[axis] = value
                    base = name_prefix_keep + rest[len(prefix):]
                    break

        # The base table both renames a base and places it inside a family, by
        # supplying the option values that distinguish it there. Applied first so
        # display-name tokens and per-item overrides still win.
        # `as` and `pack` are reserved: everything else is an option value.
        rule = bases.get(base)
        if rule:
            for axis, value in rule.items():
                if axis == "as":
                    base = str(value)
                elif axis == "pack":
                    pack_override = str(value)
                else:
                    values[axis] = str(value)

        # Parts read out of the composed name. Same standing as display-name
        # tokens, which follow and may override them.
        values.update(parts)

        position = 0
        for tok in toks:
            if tok in splitters:
                extra.append(splitters[tok])
            elif tok in tokens:
                axis, value = tokens[tok]
                if position < len(positional):
                    axis = positional[position]
                position += 1
                values[axis] = value
            else:
                unknown.add(tok)

        lowered = item.name.lower()
        for prefix, (axis, value) in prefixes.items():
            if lowered.startswith(prefix.lower()):
                values[axis] = value
        for suffix, (axis, value) in suffixes.items():
            if lowered.endswith(suffix.lower()):
                values[axis] = value

        override = per_item.get(lowered) or {}
        for axis, value in override.items():
            values[axis] = str(value)

        # Keyed on (config root, label), not the pack: a mod and an add-on that
        # extends it name the same weapon the same way, and they belong in one
        # arsenal entry -- BWMod's "G36A1" and BWA3 Add's "G36A1 (White)" share the
        # base "G36A1" and should differ only by camo. The root has to stay in the
        # key because a model is emitted under exactly one of them, so a helmet and
        # a pair of goggles sharing a display name cannot be one model.
        label = base + "".join(f" ({e})" for e in extra)
        key = (item.config_root, label)
        grouped[key].append(Member(item, values))
        if pack_override:
            forced_pack[key] = pack_override

    models: list[Model] = []
    notes: list[str] = []
    pack_order = modinfo.load().pack_order

    for key in sorted(grouped):
        config_root, label = key
        members = grouped[key]
        if len(members) < 2:
            continue

        # the entry still lives in one pack, for its class name and file path:
        # whichever contributes most members, ties going to the earlier source
        counts = collections.Counter(m.item.pack for m in members)
        pack = forced_pack.get(key) or min(
            counts, key=lambda p: (-counts[p], pack_order.get(p, 1 << 30), p)
        )

        axes_used = {axis for m in members for axis in m.values}
        # fill defaults so every member has a value on every axis this group uses
        for m in members:
            for axis in axes_used:
                m.values.setdefault(axis, str(opts[axis]["default"]))

        # an axis everyone agrees on offers no choice
        axes = [a for a in ov["option_order"] if a in axes_used and len({m.values[a] for m in members}) > 1]
        for m in members:
            m.values = {a: m.values[a] for a in axes}
        if not axes:
            notes.append(f"[{pack}] {label}: {len(members)} items but no distinguishing option")
            continue

        model = Model(
            pack=pack,
            config_root=config_root,
            label=label,
            name=f"{modinfo.load().model_prefix}_{pack}_{slug(label)}",
            author=model_author(config, config_root, members[0].item.name),
            axes=axes,
            members=sorted(members, key=lambda m: m.item.name.lower()),
            member_packs=tuple(sorted(counts)),
        )
        model.axis_values = {a: order_values(a, members, ov) for a in axes}
        combos = 1
        for a in axes:
            combos *= len(model.axis_values[a])
        model.sparse = combos > len(members)
        models.append(model)

    # emitted order stays (root, pack, label), so the #include lists are stable
    models.sort(key=lambda m: (m.config_root, m.pack, m.label))

    # Entries are grouped by (config root, label) but the class name is built from
    # pack and label alone, so two entries that differ ONLY by root collide. VSM's
    # Peltor headset is both CfgWeapons headgear and CfgGlasses facewear under one
    # display name -- correctly two arsenal rows, but one class name, which Arma
    # rejects outright ("class defined multiple times").
    #
    # Renaming only the loser keeps every existing compat byte-identical: with no
    # collision this loop does nothing. Sorted order above makes which one loses
    # deterministic.
    seen: dict[str, Model] = {}
    for model in models:
        if model.name not in seen:
            seen[model.name] = model
            continue
        stem = f"{model.name}_{model.config_root.lower().removeprefix('cfg')}"
        candidate, n = stem, 2
        while candidate in seen:
            candidate, n = f"{stem}{n}", n + 1
        notes.append(
            f"[{model.pack}] {model.label}: name clashes with the {seen[model.name].config_root} "
            f"entry of the same name -- emitted as {candidate}"
        )
        model.name = candidate
        seen[candidate] = model

    return models, notes, unknown


def model_author(config: Config, config_root: str, item_name: str) -> str:
    """Credit the item's own author, falling back to the mod's name.

    `author` is frequently a stringtable key rather than a literal (BWmod points
    every weapon at $STR_BWA3_Author), so it goes through the same resolution as
    displayName. If the key is not in any dumped stringtable it stays a raw $STR_
    reference, which would show verbatim in the arsenal -- use the mod name then.
    """
    resolved = config.text(config.resolve(config_root, item_name, "author", "")).strip()
    if not resolved or resolved.startswith("$"):
        return modinfo.load().source_name
    return resolved


def order_values(axis: str, members: list[Member], ov: dict) -> list[str]:
    """Stable, meaningful value order: the declaration order in overrides.yml."""
    canonical = [str(ov["options"][axis]["default"])]
    # the shared option class lists its values in a deliberate order; follow it.
    # `camo` has no shared class (it inherits CamoBase), so fall back to the token
    # table, and to the base table for values only families introduce.
    base = ov["options"][axis].get("base")
    for meta in ov["option_bases"].values():
        if meta["class"] == base:
            canonical += [str(v) for v in meta["values"]]
    # the camo axes share one palette, so they share one ordering: a token mapped
    # to `camo` also fixes where that colour sits in the `pantscamo` dropdown,
    # which is the only way values moved there by positional_axes get an order
    camo_axes = [str(a) for a in (ov.get("camo_axes") or ["camo"])]
    wanted = set(camo_axes) if axis in camo_axes else {axis}
    canonical += [str(v) for _, (a, v) in ov["tokens"].items() if a in wanted]
    canonical += [str(v) for _, (a, v) in ov["class_suffixes"].items() if a == axis]
    canonical += [
        str(v) for _, (a, v) in (ov.get("class_prefixes") or {}).items() if a == axis
    ]
    used = {m.values[axis] for m in members}
    ordered = [v for v in dict.fromkeys(canonical) if v in used]
    # anything introduced only by a per-weapon override lands at the end
    ordered += sorted(used - set(ordered))
    return ordered


def find_unlabelled_camo(models: list[Model], ov: dict) -> list[str]:
    """Every camo value must resolve to a label somewhere.

    `camo` is a conventional option name, so aceax looks its values up in
    XtdGearModels >> Conventional >> camo, which inherits CamoBase -- the palette
    aceax_gearinfo ships plus whatever we merge into it. A value in neither shows
    up in the arsenal as its bare name.

    `pantscamo` is the other conventional option that inherits CamoBase, so a
    compat using it lists both in `camo_axes:`.
    """
    axes = [str(a) for a in (ov.get("camo_axes") or ["camo"])]
    known = {str(v) for v in ov["camo_values_from_aceax"]} | set(ov["camo_values"])
    missing = []
    for model in models:
        for axis in axes:
            for value in model.axis_values.get(axis, []):
                if value not in known:
                    missing.append(
                        f"{model.name}: {axis} value {value!r} has no CamoBase entry"
                    )
    return missing


def find_mixed_kinds(models: list[Model]) -> list[str]:
    """No model may span two arsenal tabs.

    ACEAX collapses a model's members within one panel, so a model holding both a
    primary and a handgun would hide one of them behind a dropdown on the wrong tab.
    hlc_smg_mp5k is the live case: rifle-rooted but type 2, so it belongs with the
    pistols and must not join the MP5 family.

    Grouping is keyed on the config root, which is not enough on its own: headgear,
    uniforms and vests are all CfgWeapons but three separate tabs, so a careless
    `bases:` line could merge a helmet with a plate carrier.
    """
    problems = []
    for model in models:
        kinds = {m.item.kind for m in model.members}
        if len(kinds) > 1:
            members = ", ".join(f"{m.item.name}({m.item.kind})" for m in model.members)
            problems.append(f"{model.name}: spans arsenal tabs {sorted(kinds)} -- {members}")
    return problems


def find_order_dependent(models: list[Model]) -> list[str]:
    """Models where selecting some variant relies on the weak-match fallback.

    See modconfig.unproven_variants: these usually work, but the config alone cannot
    prove it, so they are warnings rather than errors. Practically they mark the
    groupings that are riskiest to edit.
    """
    warnings = []
    for model in models:
        variations = {
            tuple(m.values[a] for a in model.axes): m.item.name for m in model.members
        }
        unproven = unproven_variants(
            variations, [model.axis_values[a] for a in model.axes]
        )
        if unproven:
            warnings.append(
                f"{model.name}: {len(unproven)} variant(s) reachable only via the "
                f"weak-match fallback -- {', '.join(unproven[:3])}"
                + (" ..." if len(unproven) > 3 else "")
            )
    return warnings


def find_duplicates(models: list[Model]) -> list[str]:
    problems = []
    for model in models:
        seen: dict[tuple[str, ...], str] = {}
        for m in model.members:
            key = tuple(m.values[a] for a in model.axes)
            if key in seen:
                problems.append(
                    f"{model.name}: {seen[key]} and {m.item.name} both map to "
                    + "+".join(key)
                )
            seen.setdefault(key, m.item.name)
    return problems


# ---------------------------------------------------------------------------
# emitting
# ---------------------------------------------------------------------------


def q(text: str) -> str:
    return '"' + str(text).replace('"', '""') + '"'


def render_common(ov: dict) -> str:
    out = [BANNER, "\n"]

    out.append("// Extra finishes merged into the palette aceax_gearinfo already provides.\n")
    out.append("// Values such as BLK/TAN/GRN/OD/BLU/FDE are reused from there and\n")
    out.append("// deliberately not repeated.\n")
    out.append("class CamoBase\n{\n")
    for name, meta in ov["camo_values"].items():
        out.append(f"    class {name}\n    {{\n")
        out.append(f"        label = {q(meta['label'])};\n")
        if meta.get("description"):
            out.append(f"        description = {q(meta['description'])};\n")
        if meta.get("color"):
            r, g, b = meta["color"]
            out.append(f'        image = "#(rgb,8,8,3)color({r},{g},{b},1)";\n')
        out.append("    };\n")
    out.append("};\n\n")

    out.append("// Shared option definitions. Models inherit these so labels and value\n")
    out.append("// descriptions are written once, the way compat_rhs does with rhs_attachsys.\n")
    for axis, meta in ov["option_bases"].items():
        out.append(f"class {meta['class']}\n{{\n")
        out.append(f"    label = {q(meta['label'])};\n")
        out.append("    changeingame = 0;\n")
        out.append("    values[] = {};\n")
        for value, vmeta in meta["values"].items():
            out.append(f"    class {value}\n    {{\n")
            out.append(f"        label = {q(vmeta['label'])};\n")
            if vmeta.get("description"):
                out.append(f"        description = {q(vmeta['description'])};\n")
            out.append("    };\n")
        out.append("};\n\n")

    return "".join(out)


def render_model(model: Model, ov: dict) -> str:
    out = [BANNER, f"class {model.name}\n{{\n"]
    out.append(f"    label = {q(model.label)};\n")
    out.append(f"    author = {q(model.author)};\n")
    out.append("    options[] = {" + ", ".join(q(a) for a in model.axes) + "};\n")
    for axis in model.axes:
        base = ov["options"][axis].get("base")
        header = f"    class {axis} : {base}" if base else f"    class {axis}"
        out.append(header + "\n    {\n")
        out.append(
            "        values[] = {"
            + ", ".join(q(v) for v in model.axis_values[axis])
            + "};\n"
        )
        if model.sparse:
            out.append("        alwaysSelectable = 1;\n")
        out.append("    };\n")
    out.append("};\n")
    return "".join(out)


def render_infos(model: Model) -> str:
    out = [BANNER]
    for m in model.members:
        out.append(f"class {m.item.name}\n{{\n")
        out.append(f"    model = {q(model.name)};\n")
        for axis in model.axes:
            out.append(f"    {axis} = {q(m.values[axis])};\n")
        out.append("};\n")
    return "".join(out)


def render_index(models: list[Model], tree: str) -> str:
    """One `class <ConfigRoot>` block per root that has models.

    Backpacks live in CfgVehicles and facewear in CfgGlasses, so a gear compat
    emits up to three of these. The same model class name may appear under two
    roots without clashing -- they are different config paths, and ACEAX always
    looks a model up under the root of the item that referenced it.
    """
    out = [BANNER, f"class {tree}\n{{\n"]
    if tree == "XtdGearModels":
        out.append('    #include "XtdGearModels_Common.hpp"\n')
    for root in sorted({m.config_root for m in models}):
        in_root = [m for m in models if m.config_root == root]
        out.append(f"    class {root}\n    {{\n")
        for pack in sorted({m.pack for m in in_root}):
            out.append(f"        // {pack}\n")
            for model in [m for m in in_root if m.pack == pack]:
                out.append(f'        #include "{tree}\\{pack}\\{root}\\{model.name}.hpp"\n')
        out.append("    };\n")
    out.append("};\n")
    return "".join(out)


def render_config_cpp() -> str:
    mod = modinfo.load()
    return f"""class CfgPatches
{{
    class {mod.patch_class}
    {{
        name = {q(mod.name)};
        units[] = {{}};
        weapons[] = {{}};
        requiredVersion = "1.0";
        // Deliberately only aceax_gearinfo: listing the {mod.source_name} addons here
        // would stop the mod loading without it. XtdGearInfos references the source
        // classes by name, so nothing breaks when they are absent.
        requiredAddons[] = {{"aceax_gearinfo"}};
        author = {q(mod.author)};
        version = {q(mod.version)};
    }};
}};

#include "XtdGearModels.hpp"

#include "XtdGearInfos.hpp"
"""


def write(path: Path, text: str, written: set[Path]) -> bool:
    written.add(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    old = path.read_text(encoding="utf-8") if path.is_file() else None
    if old == text:
        return False
    path.write_text(text, encoding="utf-8", newline="\n")
    return True


def emit(models: list[Model], ov: dict) -> tuple[int, int]:
    written: set[Path] = set()
    changed = 0

    changed += write(ADDON / "config.cpp", render_config_cpp(), written)
    changed += write(ADDON / "XtdGearModels_Common.hpp", render_common(ov), written)
    changed += write(ADDON / "XtdGearModels.hpp", render_index(models, "XtdGearModels"), written)
    changed += write(ADDON / "XtdGearInfos.hpp", render_index(models, "XtdGearInfos"), written)

    for model in models:
        rel = Path(model.pack) / model.config_root / f"{model.name}.hpp"
        changed += write(ADDON / "XtdGearModels" / rel, render_model(model, ov), written)
        changed += write(ADDON / "XtdGearInfos" / rel, render_infos(model), written)

    # drop generated files that no longer correspond to a model
    removed = 0
    for tree in ("XtdGearModels", "XtdGearInfos"):
        for stale in sorted((ADDON / tree).rglob("*.hpp")):
            if stale not in written:
                stale.unlink()
                removed += 1
    return changed, removed


# ---------------------------------------------------------------------------


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="report only, write nothing")
    parser.add_argument("--list", action="store_true", help="print every model and its axes")
    args = parser.parse_args()

    ov = yaml.safe_load(OVERRIDES.read_text(encoding="utf-8"))
    config = Config.load()
    models, notes, unknown = collect(config, ov)

    items = config.arsenal_items()
    covered = sum(len(m.members) for m in models)
    print(
        f"{len(models)} models covering {covered}/{len(items)} arsenal-visible "
        f"{modinfo.load().source_names} items"
    )

    if args.list:
        kind_of = {i.name: i.kind for i in items}
        for m in models:
            axes = "  ".join(f"{a}[{'/'.join(m.axis_values[a])}]" for a in m.axes)
            kind = kind_of.get(m.members[0].item.name, "?")
            print(
                f"  {kind:<10}{m.pack:<16}{m.label:<34}{len(m.members):>3}  {axes}"
                + ("  SPARSE" if m.sparse else "")
            )

    if notes:
        print(f"\nskipped {len(notes)} group(s) with no distinguishing option:")
        for n in notes:
            print(f"  {n}")

    if unknown:
        print(f"\n{len(unknown)} unmapped displayName token(s) -- add to overrides.yml tokens:")
        for t in sorted(unknown):
            print(f"  {t!r}")

    # Usually vanilla classes the source mod only patches, whose displayName lives
    # on the vanilla class and so is not in the dump. Nothing to do about them --
    # they belong to a vanilla compat -- but they should not vanish silently.
    unnamed = config.unnamed_items()
    if unnamed:
        print(f"\n{len(unnamed)} item(s) skipped: no display name to group on")
        for i in unnamed[:10]:
            print(f"  {i.kind:<10} {i.name}")
        if len(unnamed) > 10:
            print(f"  ... and {len(unnamed) - 10} more")

    spanning = [m for m in models if len(m.member_packs) > 1]
    if spanning:
        print(f"\n{len(spanning)} entr(y/ies) merged across sources:")
        for m in spanning:
            print(f"  {m.label:<28} {'+'.join(m.member_packs)}  -> {m.name}")

    order_dependent = find_order_dependent(models)
    if order_dependent:
        print(f"\nwarning: {len(order_dependent)} model(s) depend on weak-match ordering:")
        for w in order_dependent:
            print(f"  {w}")

    problems = (
        find_duplicates(models)
        + find_mixed_kinds(models)
        + find_unlabelled_camo(models, ov)
    )
    if problems:
        print(f"\n{len(problems)} problem(s) aceax would reject or render badly:")
        for p in problems:
            print(f"  {p}")
        return 1

    if args.check:
        return 0

    changed, removed = emit(models, ov)
    print(f"\nwrote {changed} changed file(s), removed {removed} stale file(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
